export const STRINGS: Record<string, Record<string, string>> = {
  en: {
    rescan: "Rescan",
    install: "Install kit",
    installing: "Installing…",
    addKit: "Add",
    addKitToggle: "+ Add kit by URL",
    addKitPlaceholder: "https://…/kit.json",
    adding: "Verifying…",
    cancel: "Cancel",
    removeKit: "Remove kit",
    removeKitConfirm: "Remove kit?",
    everything: "Everything installed",
    ofInstalled: "installed",
    serversAuthorized: "authorized",
    noClients: "No supported clients found",
    installed: "Installed",
    adopt: "Take over",
    adoptHint: "Added outside CrewKit — click to take over management",
    notInstalled: "Not installed",
    authorized: "authorized",
    authorize: "Authorize",
    waitingBrowser: "Waiting for browser…",
    logout: "Log out",
    loggingOut: "Logging out…",
    remove: "Remove",
    removeConfirm: "Remove everywhere?",
    removing: "Removing…",
    details: "Details",
    copyLog: "Copy",
    copied: "Copied",
    restart: "Restart",
    restartTail: "to pick up the changes",
    scanning: "Scanning this computer…",
    updateAvailable: "CrewKit {v} is available",
    installUpdate: "Update & restart",
    updating: "Updating…",
    telemetryNote: "Reports installs to the publisher",
    telemetryWhat: "what is collected",
    channel: "Channel",
    bundle: "Bundle",
    chooseOptions: "Choose how to install this kit",
    continue: "Continue",
    backgroundUpdating: "Updating in the background…",
    newInBundle: "New in your bundle",
    notifKitUpdated: "{kit} updated",
    notifNewItems: "New in {kit}",
    notifNewItemsBody: "Open CrewKit to install: {items}",
    notifRestart: "Restart {clients}",
    notifRestartBody: "to pick up the updated kit",
    notifAppUpdated: "CrewKit updated to {v}",
    signedBy: "signed · key pinned",
    builtin: "built into the app",
    found: "found",
    notFound: "not found",
    failedShort: "failed",
    retry: "Retry",
    kitUnavailable: "Kit unavailable",
    signIn: "Sign in",
    kitNeedsSignIn: "This kit is published for a signed-in audience — sign in to download it",
    needSignIn: "Servers waiting for sign-in: {n}",
    signingIn: "Signing in — {i} of {n}…",
    later: "Later",
    noRenewTip: "This server issues no renewal token, so it will ask for a sign-in again once the session ends.",
    emptyTitle: "No kits yet",
    emptyHint: "Paste a kit manifest URL from your publisher, or open a crewkit:// link.",
    mcpGroup: "MCP Servers",
    pluginGroup: "Plugins",
    installShort: "Install",
    removeQ: "Remove?",
    installAllTo: "Install all to {app}",
    removeAllFrom: "Remove all from {app}",
    confirmAgain: "Click again to confirm",
    selectedN: "{n} selected",
    installToLabel: "Install to",
    both: "Both",
    clearSel: "Clear",
    removeFrom: "Remove from {app}",
    installToApp: "Install to {app}",
    notSupported: "Not supported",
    notSupportedTip: "Transport `{t}` needs a newer CrewKit version.",
    wherePluginClaudeCode: "Plugin for the CLI and the Code tab",
    whereMcpClaudeCode: "Server via CrewKit bridge, CLI and the Code tab",
    wherePluginClaudeDesktop: "Plugin for Cowork sessions",
    whereMcpClaudeDesktop: "Server via CrewKit bridge, Desktop chat and Cowork",
    wherePluginCodex: "Plugin for Codex CLI and the ChatGPT app",
    whereMcpCodex: "Server via CrewKit bridge, Codex CLI and the ChatGPT app",
    sharesCodex: "shares the Codex config",
    noteForeign: "`{id}` was added outside CrewKit",
    noteNoCoworkProfile: "Open Cowork once so it creates its profile",
  },
  ru: {
    rescan: "Обновить",
    install: "Установить",
    installing: "Установка…",
    addKit: "Добавить",
    addKitToggle: "+ Добавить кит по URL",
    addKitPlaceholder: "https://…/kit.json",
    adding: "Проверка…",
    cancel: "Отмена",
    removeKit: "Убрать кит",
    removeKitConfirm: "Убрать кит?",
    everything: "Всё установлено",
    ofInstalled: "установлено",
    serversAuthorized: "авторизовано",
    noClients: "Клиенты не найдены",
    installed: "Установлено",
    adopt: "Взять на себя",
    adoptHint: "Добавлено вне CrewKit — нажмите, чтобы CrewKit взял управление на себя",
    notInstalled: "Не установлено",
    authorized: "авторизован",
    authorize: "Авторизовать",
    waitingBrowser: "Ждём браузер…",
    logout: "Выйти",
    loggingOut: "Выходим…",
    remove: "Удалить",
    removeConfirm: "Удалить везде?",
    removing: "Удаляем…",
    details: "Детали",
    copyLog: "Скопировать",
    copied: "Скопировано",
    restart: "Перезапустите",
    restartTail: "чтобы подхватить изменения",
    scanning: "Сканируем этот компьютер…",
    updateAvailable: "Доступен CrewKit {v}",
    installUpdate: "Обновить и перезапустить",
    updating: "Обновляем…",
    telemetryNote: "Сообщает издателю об установках",
    telemetryWhat: "что собирается",
    channel: "Канал",
    bundle: "Набор",
    chooseOptions: "Выберите, как установить этот кит",
    continue: "Продолжить",
    backgroundUpdating: "Идёт фоновое обновление…",
    newInBundle: "Новое в вашем наборе",
    notifKitUpdated: "{kit} обновлён",
    notifNewItems: "Новое в {kit}",
    notifNewItemsBody: "Откройте CrewKit, чтобы установить: {items}",
    notifRestart: "Перезапустите {clients}",
    notifRestartBody: "чтобы подхватить обновлённый кит",
    notifAppUpdated: "CrewKit обновлён до {v}",
    signedBy: "подписан · ключ закреплён",
    builtin: "встроен в приложение",
    found: "найден",
    notFound: "не найден",
    failedShort: "с ошибкой",
    retry: "Повторить",
    kitUnavailable: "Кит недоступен",
    signIn: "Войти",
    kitNeedsSignIn: "Кит закрыт авторизацией — войдите, чтобы скачать его",
    needSignIn: "Ожидают входа: {n}",
    signingIn: "Вход — {i} из {n}…",
    later: "Позже",
    noRenewTip: "Этот сервер не выдаёт токен продления, поэтому попросит войти заново, когда сессия закончится.",
    emptyTitle: "Пока нет китов",
    emptyHint: "Вставьте URL манифеста от вашего издателя или откройте crewkit://-ссылку.",
    mcpGroup: "MCP-серверы",
    pluginGroup: "Плагины",
    installShort: "Установить",
    removeQ: "Удалить?",
    installAllTo: "Установить всё в {app}",
    removeAllFrom: "Удалить всё из {app}",
    confirmAgain: "Нажмите ещё раз для подтверждения",
    selectedN: "выбрано: {n}",
    installToLabel: "Установить в",
    both: "Оба",
    clearSel: "Сбросить",
    removeFrom: "Удалить из {app}",
    installToApp: "Установить в {app}",
    notSupported: "Не поддерживается",
    notSupportedTip: "Транспорт `{t}` требует более новой версии CrewKit.",
    wherePluginClaudeCode: "Плагин для CLI и вкладки Code",
    whereMcpClaudeCode: "Сервер через CrewKit bridge, CLI и вкладка Code",
    wherePluginClaudeDesktop: "Плагин для сессий Cowork",
    whereMcpClaudeDesktop: "Сервер через CrewKit bridge, чат Desktop и Cowork",
    wherePluginCodex: "Плагин для Codex CLI и приложения ChatGPT",
    whereMcpCodex: "Сервер через CrewKit bridge, Codex CLI и приложение ChatGPT",
    sharesCodex: "общий конфиг с Codex",
    noteForeign: "`{id}` добавлен вне CrewKit",
    noteNoCoworkProfile: "Откройте Cowork один раз, чтобы он создал профиль",
  },
  es: {
    rescan: "Reescanear",
    install: "Instalar kit",
    installing: "Instalando…",
    addKit: "Añadir",
    addKitToggle: "+ Añadir kit por URL",
    addKitPlaceholder: "https://…/kit.json",
    adding: "Verificando…",
    cancel: "Cancelar",
    removeKit: "Quitar kit",
    removeKitConfirm: "¿Quitar kit?",
    everything: "Todo instalado",
    ofInstalled: "instalado",
    serversAuthorized: "autorizados",
    noClients: "No se encontraron clientes compatibles",
    installed: "Instalado",
    adopt: "Gestionar",
    adoptHint: "Añadido fuera de CrewKit — haz clic para que CrewKit lo gestione",
    notInstalled: "No instalado",
    authorized: "autorizado",
    authorize: "Autorizar",
    waitingBrowser: "Esperando al navegador…",
    logout: "Cerrar sesión",
    loggingOut: "Cerrando sesión…",
    remove: "Eliminar",
    removeConfirm: "¿Eliminar de todos?",
    removing: "Eliminando…",
    details: "Detalles",
    copyLog: "Copiar",
    copied: "Copiado",
    restart: "Reinicia",
    restartTail: "para aplicar los cambios",
    scanning: "Escaneando este equipo…",
    updateAvailable: "CrewKit {v} disponible",
    installUpdate: "Actualizar y reiniciar",
    updating: "Actualizando…",
    telemetryNote: "Informa de instalaciones al editor",
    telemetryWhat: "qué se recopila",
    channel: "Canal",
    bundle: "Paquete",
    chooseOptions: "Elige cómo instalar este kit",
    continue: "Continuar",
    backgroundUpdating: "Actualizando en segundo plano…",
    newInBundle: "Nuevo en tu paquete",
    notifKitUpdated: "{kit} actualizado",
    notifNewItems: "Nuevo en {kit}",
    notifNewItemsBody: "Abre CrewKit para instalar: {items}",
    notifRestart: "Reinicia {clients}",
    notifRestartBody: "para aplicar el kit actualizado",
    notifAppUpdated: "CrewKit actualizado a {v}",
    signedBy: "firmado · clave fijada",
    builtin: "integrado en la app",
    found: "encontrado",
    notFound: "no encontrado",
    failedShort: "con error",
    retry: "Reintentar",
    kitUnavailable: "Kit no disponible",
    signIn: "Iniciar sesión",
    kitNeedsSignIn: "Este kit es privado: inicia sesión para descargarlo",
    needSignIn: "Servidores pendientes de inicio de sesión: {n}",
    signingIn: "Iniciando sesión — {i} de {n}…",
    later: "Más tarde",
    noRenewTip: "Este servidor no emite token de renovación, así que volverá a pedir inicio de sesión cuando termine la sesión.",
    emptyTitle: "Aún no hay kits",
    emptyHint: "Pega la URL del manifiesto de tu editor o abre un enlace crewkit://.",
    mcpGroup: "Servidores MCP",
    pluginGroup: "Plugins",
    installShort: "Instalar",
    removeQ: "¿Quitar?",
    installAllTo: "Instalar todo en {app}",
    removeAllFrom: "Quitar todo de {app}",
    confirmAgain: "Haz clic de nuevo para confirmar",
    selectedN: "{n} seleccionados",
    installToLabel: "Instalar en",
    both: "Ambos",
    clearSel: "Limpiar",
    removeFrom: "Quitar de {app}",
    installToApp: "Instalar en {app}",
    notSupported: "No compatible",
    notSupportedTip: "El transporte `{t}` requiere una versión más reciente de CrewKit.",
    wherePluginClaudeCode: "Plugin para la CLI y la pestaña Code",
    whereMcpClaudeCode: "Servidor vía CrewKit bridge, CLI y pestaña Code",
    wherePluginClaudeDesktop: "Plugin para sesiones de Cowork",
    whereMcpClaudeDesktop: "Servidor vía CrewKit bridge, chat de Desktop y Cowork",
    wherePluginCodex: "Plugin para Codex CLI y la app de ChatGPT",
    whereMcpCodex: "Servidor vía CrewKit bridge, Codex CLI y la app de ChatGPT",
    sharesCodex: "comparte la configuración de Codex",
    noteForeign: "`{id}` se añadió fuera de CrewKit",
    noteNoCoworkProfile: "Abre Cowork una vez para que cree su perfil",
  },
  zh: {
    rescan: "重新扫描",
    install: "安装套件",
    installing: "安装中…",
    addKit: "添加",
    addKitToggle: "+ 通过 URL 添加套件",
    addKitPlaceholder: "https://…/kit.json",
    adding: "验证中…",
    cancel: "取消",
    removeKit: "移除套件",
    removeKitConfirm: "移除套件？",
    everything: "全部已安装",
    ofInstalled: "已安装",
    serversAuthorized: "已授权",
    noClients: "未找到支持的客户端",
    installed: "已安装",
    adopt: "接管",
    adoptHint: "在 CrewKit 之外添加 — 点击由 CrewKit 接管",
    notInstalled: "未安装",
    authorized: "已授权",
    authorize: "授权",
    waitingBrowser: "等待浏览器…",
    logout: "退出登录",
    loggingOut: "正在退出…",
    remove: "移除",
    removeConfirm: "从所有客户端移除？",
    removing: "移除中…",
    details: "详情",
    copyLog: "复制",
    copied: "已复制",
    restart: "请重启",
    restartTail: "以应用更改",
    scanning: "正在扫描此电脑…",
    updateAvailable: "CrewKit {v} 已发布",
    installUpdate: "更新并重启",
    updating: "更新中…",
    telemetryNote: "向发布者报告安装情况",
    telemetryWhat: "收集内容",
    channel: "通道",
    bundle: "套装",
    chooseOptions: "选择如何安装此套件",
    continue: "继续",
    backgroundUpdating: "正在后台更新…",
    newInBundle: "套装中的新内容",
    notifKitUpdated: "{kit} 已更新",
    notifNewItems: "{kit} 有新内容",
    notifNewItemsBody: "打开 CrewKit 安装：{items}",
    notifRestart: "请重启 {clients}",
    notifRestartBody: "以应用更新后的套件",
    notifAppUpdated: "CrewKit 已更新到 {v}",
    signedBy: "已签名 · 密钥已固定",
    builtin: "内置于应用",
    found: "已找到",
    notFound: "未找到",
    failedShort: "失败",
    retry: "重试",
    kitUnavailable: "套件不可用",
    signIn: "登录",
    kitNeedsSignIn: "该套件需要登录后才能下载",
    needSignIn: "等待登录的服务器：{n}",
    signingIn: "正在登录 — 第 {i} 个，共 {n} 个…",
    later: "稍后",
    noRenewTip: "该服务器不签发续期令牌，会话结束后会再次要求登录。",
    emptyTitle: "还没有套件",
    emptyHint: "粘贴发布者提供的清单 URL，或打开 crewkit:// 链接。",
    mcpGroup: "MCP 服务器",
    pluginGroup: "插件",
    installShort: "安装",
    removeQ: "移除？",
    installAllTo: "全部安装到 {app}",
    removeAllFrom: "从 {app} 移除全部",
    confirmAgain: "再次点击以确认",
    selectedN: "已选 {n} 项",
    installToLabel: "安装到",
    both: "两者",
    clearSel: "清除",
    removeFrom: "从 {app} 移除",
    installToApp: "安装到 {app}",
    notSupported: "不支持",
    notSupportedTip: "传输协议 `{t}` 需要更新版本的 CrewKit。",
    wherePluginClaudeCode: "用于 CLI 和 Code 标签页的插件",
    whereMcpClaudeCode: "通过 CrewKit bridge 的服务器，CLI 和 Code 标签页",
    wherePluginClaudeDesktop: "用于 Cowork 会话的插件",
    whereMcpClaudeDesktop: "通过 CrewKit bridge 的服务器，Desktop 聊天和 Cowork",
    wherePluginCodex: "用于 Codex CLI 和 ChatGPT 应用的插件",
    whereMcpCodex: "通过 CrewKit bridge 的服务器，Codex CLI 和 ChatGPT 应用",
    sharesCodex: "与 Codex 共用配置",
    noteForeign: "`{id}` 是在 CrewKit 之外添加的",
    noteNoCoworkProfile: "请先打开一次 Cowork 以创建其配置",
  },
};

export let lang = localStorage.getItem("crewkit-lang") ?? "en";

export function setLang(code: string): void {
  lang = code;
  localStorage.setItem("crewkit-lang", code);
}

export const t = (key: string): string => STRINGS[lang]?.[key] ?? STRINGS.en[key] ?? key;
